# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Helper Functions --------------------------------------------------------
from subprocess import Popen, PIPE

def getVersion():
    revString    = Popen('git describe --always --tags',    stdout = PIPE, shell = True).stdout.read().rstrip()
    return revString.decode('ascii')

def getBranch():
    branchString = Popen('git rev-parse --abbrev-ref HEAD', stdout = PIPE, shell = True).stdout.read().rstrip()
    return branchString.decode('ascii')

def getRelease():
    return "{version} ({branch})".format(branch=getBranch(), version=getVersion())

def getDocRoot():
    path = Popen('git rev-parse --show-toplevel', stdout = PIPE, shell = True).stdout.read().rstrip()
    return path.decode('ascii')

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = u'Igor Unit Testing Framework'
copyright = u'2018, Thomas Braun, Michael Huth, Matthias Kastner'
author = u'Thomas Braun, Michael Huth, Matthias Kastner'

version = getVersion()
release = getRelease()


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.mathjax',
    'sphinxcontrib.fulltoc',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'
pygments_style     = 'igor'
highlight_language = 'igor'

todo_include_todos = False

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'github_user': 'byte-physics',
    'github_repo': 'igor-unit-testing-framework',
    'github_banner': True,
    'show_powered_by': False,
    'page_width' : '90%',
}

html_context = {
    'branch' : getBranch(),
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
html_sidebars = {
        '**': ['logo.html', 'localtoc.html', 'searchbox.html', 'version.html'],
        }

# the html_logo always links to the main page.
#html_logo = '_static/images/logo/bp-logo.png'

# open javascript analytics: https://matomo.org/
def setup(app):
    app.add_javascript('js/matomo.js')

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'IgorUnitTestingFrameworkdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'IgorUnitTestingFramework.tex', u'Igor Unit Testing Framework Documentation',
     u'byte-physics.de', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'igorunittestingframework', u'Igor Unit Testing Framework Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'IgorUnitTestingFramework', u'Igor Unit Testing Framework Documentation',
     author, 'IgorUnitTestingFramework',
     u'A unit testing framework for Wavemetrics Igor Pro', 'byte-physics'),
]


# -- Extension configuration -------------------------------------------------

# breathe
breathe_projects            = { "igor-utf": "xml" }
breathe_default_project     = "igor-utf"
breathe_domain_by_extension = { "ipf" : "cpp" }
breathe_default_members     = ('members', 'undoc-members')

cpp_id_attributes = [ 'threadsafe', 'static', 'const', 'variable/c', 'variable' ]
cpp_paren_attributes = [ ]

# dot
graphviz_output_format = 'svg'
